steps:
# Instalar dependencias
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'resume'

# Compilar la aplicación Angular
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'resume'

# Mover la carpeta dist a otra ubicación
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['mv', 'resume/dist', 'container']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'pierinho13/resume:$COMMIT_SHA', 'container']

  # Sube la imagen Docker a Docker hub
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'pierinho13/resume:$COMMIT_SHA']
