steps:
# Instalar dependencias
# Despliega la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'resume-cv'
    - '--image'
    - 'pierinho13/resume:latest'
    - '--region'
    - 'europe-west1'