steps:
  # Construye la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/igeopre/sretask:$COMMIT_SHA', 'sre-task']

  # Sube la imagen Docker a Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/igeopre/sretask:$COMMIT_SHA']

  # Despliega la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'sretask'
    - '--image'
    - 'gcr.io/$PROJECT_ID/sretask:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'